# Site settings
title: Loveforgeter's Blog
email: loveforgeter@gmail.com
description: happy hacking
baseurl: ""
url: "loveforgeter.com"
github_username:  loveforgeter
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year-:month-:day/:title.html
gems:
    - jekyll-archives
