# Site settings
title: Loveforgeter's Blog
email: loveforgeter@gmail.com
description: happy hacking
baseurl: ""
url: "loveforgeter.com"
github_username:  loveforgeter
markdown: kramdown
highlighter: pygments
permalink: /blog/:year-:month-:day/:title.html
